export enum Message {
    OTP_SENT = 'Otp has been sent to your email.',
    UNAUTHORIZED = 'Email or password Wrong',
    LOGGED_IN = 'Logged in successfully',
    USER_ALREADY_EXIST = 'User already exist.',
    MAIL_ERR = 'Some error occurred while sending e-mail, please try again after some time.',
    USER_NOT_FOUND = 'User not found with this email',
    INVALID_OTP = 'Invalid otp',
    OTP_VERIFIED = 'Otp Verified successfully',
    SAME_PASSWORD = 'Passwords can not be same',
    PASS_CHANGED = 'Password changed successfully',
    WRONG_PASS = 'Wrong password',
    INVALID_EMAIL = 'Invalid Email!',
    CHAT_CREATED = 'Chat created successfully',
    SOMETHING_WENT_WRONG = 'Something went wrong',
    CHAT_UPDATED = 'Chat updated successfully',
    CHAT_DELETED = 'Chat Deleted successfully',
    UNAUTHORIZED_OPERATION = 'You are unauthorized to perform this operation',
}
